name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.10.4
      uses: actions/setup-go@v1
      with:
        go-version: 1.10.4
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get Dependencies
      run: |
        echo $GOBIN
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure -vendor-only -v
        fi

    - name: Build
      run: go build -v .

    - name: Run Go Tests
      run: go test -v -cover -race

    - name: Run golangci-lint with reviewdog
      uses: reviewdog/action-golangci-lint@v1.0.4

    # - name: Build the Docker image
      # run: docker build . --file ./.github/golangci/Dockerfile
  
    # - name: Go steps and GolangCI-lint
      # uses: ./.github/golangci/
