name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.10
      uses: actions/setup-go@v1
      with:
        go-version: 1.10
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Go steps and GolangCI-lint
      uses: ./.github/golangci/
