name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.21.3
      uses: actions/setup-go@v1
      with:
        go-version: 1.21.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure -vendor-only -v
        fi

    - name: Build
      run: go build -v .

    - name: Install GolangCI-lint
      run: |
        wget -c https://github.com/golangci/golangci-lint/releases/download/v1.16.0/golangci-lint-1.16.0-linux-386.tar.gz
        tar zxf golangci-lint-1.16.0-linux-386.tar.gz
        cp -v golangci-lint-1.16.0-linux-386/golangci-lint $GOPATH/bin/

    - name: Run GolangCI-lint
      run: golangci-lint run ./...

    - name: Go testing
      run: go test -v -cover -race $(go list ./... | grep -v vendor/)
